model_name_or_path: /data/github/RD-Agent/finetune_files/models/Qwen/Qwen2.5-7B-Instruct
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_target: all
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.05
use_rslora: false
use_dora: false
dataset: processed_data
eval_dataset: processed_data_validation
dataset_dir: ./
tokenized_path: ./tokenized_cache
template: qwen
cutoff_len: 2048
train_on_prompt: false
ignore_pad_token_for_loss: true
packing: true
neat_packing: true
enable_thinking: false
overwrite_cache: true
preprocessing_num_workers: 8
flash_attn: fa2
gradient_checkpointing: true
use_reentrant_gc: false
bf16: true
tf32: true
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4
group_by_length: true
num_train_epochs: 4.0
learning_rate: 6.0e-05
weight_decay: 0.01
lr_scheduler_type: cosine
warmup_ratio: 0.06
max_grad_norm: 1.0
eval_strategy: epoch
save_strategy: epoch
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
save_total_limit: 1
save_only_model: false
logging_strategy: steps
logging_steps: 25
logging_first_step: true
seed: 42
data_seed: 42
dataloader_num_workers: 8
dataloader_persistent_workers: false
output_dir: ./output
